// flow-typed signature: db60cff367a368232c397cae7efa6db3
// flow-typed version: <<STUB>>/atob_v2.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atob/bin/atob' {
  declare module.exports: any;
}

declare module 'atob/browser-atob' {
  declare module.exports: any;
}

declare module 'atob/node-atob' {
  declare module.exports: any;
}

declare module 'atob/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atob/bin/atob.js' {
  declare module.exports: $Exports<'atob/bin/atob'>;
}
declare module 'atob/browser-atob.js' {
  declare module.exports: $Exports<'atob/browser-atob'>;
}
declare module 'atob/node-atob.js' {
  declare module.exports: $Exports<'atob/node-atob'>;
}
declare module 'atob/test.js' {
  declare module.exports: $Exports<'atob/test'>;
}
