// flow-typed signature: 8f0237a3fe50c4865d03589a6a736d3c
// flow-typed version: <<STUB>>/avon_vkorczis/avon#master/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'avon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'avon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'avon/streaming' {
  declare module.exports: any;
}

declare module 'avon/test/test-01-basic' {
  declare module.exports: any;
}

declare module 'avon/test/test-02-streaming' {
  declare module.exports: any;
}

// Filename aliases
declare module 'avon/index' {
  declare module.exports: $Exports<'avon'>;
}
declare module 'avon/index.js' {
  declare module.exports: $Exports<'avon'>;
}
declare module 'avon/streaming.js' {
  declare module.exports: $Exports<'avon/streaming'>;
}
declare module 'avon/test/test-01-basic.js' {
  declare module.exports: $Exports<'avon/test/test-01-basic'>;
}
declare module 'avon/test/test-02-streaming.js' {
  declare module.exports: $Exports<'avon/test/test-02-streaming'>;
}
