// flow-typed signature: d6e73ced8168926113a0d14bd4486269
// flow-typed version: <<STUB>>/base58_v^1.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base58'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base58' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base58/src/base58' {
  declare module.exports: any;
}

declare module 'base58/test/base58.test' {
  declare module.exports: any;
}

declare module 'base58/test/examples' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base58/src/base58.js' {
  declare module.exports: $Exports<'base58/src/base58'>;
}
declare module 'base58/test/base58.test.js' {
  declare module.exports: $Exports<'base58/test/base58.test'>;
}
declare module 'base58/test/examples.js' {
  declare module.exports: $Exports<'base58/test/examples'>;
}
