// flow-typed signature: 0fb3e3e87712a17e9506eb5edd964ccf
// flow-typed version: <<STUB>>/bitcoin-script_v^0.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoin-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoin-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoin-script/lib/config' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/crypto' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/index' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/key-gen' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/script-stack' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/script' {
  declare module.exports: any;
}

declare module 'bitcoin-script/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoin-script/lib/config.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/config'>;
}
declare module 'bitcoin-script/lib/crypto.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/crypto'>;
}
declare module 'bitcoin-script/lib/index.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/index'>;
}
declare module 'bitcoin-script/lib/key-gen.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/key-gen'>;
}
declare module 'bitcoin-script/lib/script-stack.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/script-stack'>;
}
declare module 'bitcoin-script/lib/script.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/script'>;
}
declare module 'bitcoin-script/lib/validator.js' {
  declare module.exports: $Exports<'bitcoin-script/lib/validator'>;
}
