// flow-typed signature: 461f0721c9cfe650599043d5786fbd71
// flow-typed version: <<STUB>>/bitpony_v0.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitpony'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitpony' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitpony/_tests/extends' {
  declare module.exports: any;
}

declare module 'bitpony/_tests/read' {
  declare module.exports: any;
}

declare module 'bitpony/_tests/write' {
  declare module.exports: any;
}

declare module 'bitpony/bitpony' {
  declare module.exports: any;
}

declare module 'bitpony/bytes/read' {
  declare module.exports: any;
}

declare module 'bitpony/bytes/tools' {
  declare module.exports: any;
}

declare module 'bitpony/bytes/write' {
  declare module.exports: any;
}

declare module 'bitpony/examples/add_new_types' {
  declare module.exports: any;
}

declare module 'bitpony/examples/json' {
  declare module.exports: any;
}

declare module 'bitpony/examples/smple' {
  declare module.exports: any;
}

declare module 'bitpony/examples/stacks' {
  declare module.exports: any;
}

declare module 'bitpony/examples/streams' {
  declare module.exports: any;
}

declare module 'bitpony/protocol/read' {
  declare module.exports: any;
}

declare module 'bitpony/protocol/write' {
  declare module.exports: any;
}

declare module 'bitpony/stack/read' {
  declare module.exports: any;
}

declare module 'bitpony/stack/write' {
  declare module.exports: any;
}

declare module 'bitpony/types/builder' {
  declare module.exports: any;
}

declare module 'bitpony/types/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitpony/_tests/extends.js' {
  declare module.exports: $Exports<'bitpony/_tests/extends'>;
}
declare module 'bitpony/_tests/read.js' {
  declare module.exports: $Exports<'bitpony/_tests/read'>;
}
declare module 'bitpony/_tests/write.js' {
  declare module.exports: $Exports<'bitpony/_tests/write'>;
}
declare module 'bitpony/bitpony.js' {
  declare module.exports: $Exports<'bitpony/bitpony'>;
}
declare module 'bitpony/bytes/read.js' {
  declare module.exports: $Exports<'bitpony/bytes/read'>;
}
declare module 'bitpony/bytes/tools.js' {
  declare module.exports: $Exports<'bitpony/bytes/tools'>;
}
declare module 'bitpony/bytes/write.js' {
  declare module.exports: $Exports<'bitpony/bytes/write'>;
}
declare module 'bitpony/examples/add_new_types.js' {
  declare module.exports: $Exports<'bitpony/examples/add_new_types'>;
}
declare module 'bitpony/examples/json.js' {
  declare module.exports: $Exports<'bitpony/examples/json'>;
}
declare module 'bitpony/examples/smple.js' {
  declare module.exports: $Exports<'bitpony/examples/smple'>;
}
declare module 'bitpony/examples/stacks.js' {
  declare module.exports: $Exports<'bitpony/examples/stacks'>;
}
declare module 'bitpony/examples/streams.js' {
  declare module.exports: $Exports<'bitpony/examples/streams'>;
}
declare module 'bitpony/protocol/read.js' {
  declare module.exports: $Exports<'bitpony/protocol/read'>;
}
declare module 'bitpony/protocol/write.js' {
  declare module.exports: $Exports<'bitpony/protocol/write'>;
}
declare module 'bitpony/stack/read.js' {
  declare module.exports: $Exports<'bitpony/stack/read'>;
}
declare module 'bitpony/stack/write.js' {
  declare module.exports: $Exports<'bitpony/stack/write'>;
}
declare module 'bitpony/types/builder.js' {
  declare module.exports: $Exports<'bitpony/types/builder'>;
}
declare module 'bitpony/types/parser.js' {
  declare module.exports: $Exports<'bitpony/types/parser'>;
}
