// flow-typed signature: 123c38f4fca7a50685ecfab78090cc2e
// flow-typed version: <<STUB>>/blockchain-spv_v^3.1.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blockchain-spv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blockchain-spv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blockchain-spv/lib/blockchain' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blockchain-spv/index' {
  declare module.exports: $Exports<'blockchain-spv'>;
}
declare module 'blockchain-spv/index.js' {
  declare module.exports: $Exports<'blockchain-spv'>;
}
declare module 'blockchain-spv/lib/blockchain.js' {
  declare module.exports: $Exports<'blockchain-spv/lib/blockchain'>;
}
