// flow-typed signature: a7f96b9e8e33945d8a50777ce252a8cb
// flow-typed version: <<STUB>>/blockchain.info_v^2.11.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blockchain.info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blockchain.info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blockchain.info/api' {
  declare module.exports: any;
}

declare module 'blockchain.info/blockexplorer/endpoints' {
  declare module.exports: any;
}

declare module 'blockchain.info/blockexplorer/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/blockexplorer/spec' {
  declare module.exports: any;
}

declare module 'blockchain.info/exchange/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/exchange/spec' {
  declare module.exports: any;
}

declare module 'blockchain.info/MyWallet/endpoints' {
  declare module.exports: any;
}

declare module 'blockchain.info/MyWallet/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/pushtx/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/Receive/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/Socket/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/statistics/index' {
  declare module.exports: any;
}

declare module 'blockchain.info/statistics/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blockchain.info/api.js' {
  declare module.exports: $Exports<'blockchain.info/api'>;
}
declare module 'blockchain.info/blockexplorer/endpoints.js' {
  declare module.exports: $Exports<'blockchain.info/blockexplorer/endpoints'>;
}
declare module 'blockchain.info/blockexplorer/index.js' {
  declare module.exports: $Exports<'blockchain.info/blockexplorer/index'>;
}
declare module 'blockchain.info/blockexplorer/spec.js' {
  declare module.exports: $Exports<'blockchain.info/blockexplorer/spec'>;
}
declare module 'blockchain.info/exchange/index.js' {
  declare module.exports: $Exports<'blockchain.info/exchange/index'>;
}
declare module 'blockchain.info/exchange/spec.js' {
  declare module.exports: $Exports<'blockchain.info/exchange/spec'>;
}
declare module 'blockchain.info/index' {
  declare module.exports: $Exports<'blockchain.info'>;
}
declare module 'blockchain.info/index.js' {
  declare module.exports: $Exports<'blockchain.info'>;
}
declare module 'blockchain.info/MyWallet/endpoints.js' {
  declare module.exports: $Exports<'blockchain.info/MyWallet/endpoints'>;
}
declare module 'blockchain.info/MyWallet/index.js' {
  declare module.exports: $Exports<'blockchain.info/MyWallet/index'>;
}
declare module 'blockchain.info/pushtx/index.js' {
  declare module.exports: $Exports<'blockchain.info/pushtx/index'>;
}
declare module 'blockchain.info/Receive/index.js' {
  declare module.exports: $Exports<'blockchain.info/Receive/index'>;
}
declare module 'blockchain.info/Socket/index.js' {
  declare module.exports: $Exports<'blockchain.info/Socket/index'>;
}
declare module 'blockchain.info/statistics/index.js' {
  declare module.exports: $Exports<'blockchain.info/statistics/index'>;
}
declare module 'blockchain.info/statistics/spec.js' {
  declare module.exports: $Exports<'blockchain.info/statistics/spec'>;
}
