// flow-typed signature: 08955d3dfdb0d3a221f21c9d885a12e3
// flow-typed version: <<STUB>>/btc-transaction_v^0.1.8/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'btc-transaction'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'btc-transaction' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'btc-transaction/lib/transaction-in' {
  declare module.exports: any;
}

declare module 'btc-transaction/lib/transaction-out' {
  declare module.exports: any;
}

declare module 'btc-transaction/lib/transaction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'btc-transaction/lib/transaction-in.js' {
  declare module.exports: $Exports<'btc-transaction/lib/transaction-in'>;
}
declare module 'btc-transaction/lib/transaction-out.js' {
  declare module.exports: $Exports<'btc-transaction/lib/transaction-out'>;
}
declare module 'btc-transaction/lib/transaction.js' {
  declare module.exports: $Exports<'btc-transaction/lib/transaction'>;
}
