// flow-typed signature: 4a2a8dfb3bf91b8ab8baeed909177e66
// flow-typed version: <<STUB>>/circular-buffer_v1.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'circular-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'circular-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'circular-buffer/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'circular-buffer/index' {
  declare module.exports: $Exports<'circular-buffer'>;
}
declare module 'circular-buffer/index.js' {
  declare module.exports: $Exports<'circular-buffer'>;
}
declare module 'circular-buffer/test/test.js' {
  declare module.exports: $Exports<'circular-buffer/test/test'>;
}
