// flow-typed signature: 5040dd53c6b7e0bb62eac0a5918adbde
// flow-typed version: <<STUB>>/compute-cosine-distance_v^1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compute-cosine-distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compute-cosine-distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compute-cosine-distance/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compute-cosine-distance/lib/index.js' {
  declare module.exports: $Exports<'compute-cosine-distance/lib/index'>;
}
