// flow-typed signature: 21f78824224bac75e84a8c2759a434df
// flow-typed version: <<STUB>>/convert-hex_v^0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'convert-hex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'convert-hex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'convert-hex/convert-hex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'convert-hex/convert-hex.js' {
  declare module.exports: $Exports<'convert-hex/convert-hex'>;
}
