// flow-typed signature: 55fcd3edf9374214993f2d6b8478b130
// flow-typed version: <<STUB>>/deepcopy_v^0.6.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepcopy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepcopy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deepcopy/build/deepcopy' {
  declare module.exports: any;
}

declare module 'deepcopy/build/deepcopy.min' {
  declare module.exports: any;
}

declare module 'deepcopy/lib/copy' {
  declare module.exports: any;
}

declare module 'deepcopy/lib/index' {
  declare module.exports: any;
}

declare module 'deepcopy/lib/polyfill' {
  declare module.exports: any;
}

declare module 'deepcopy/src/copy' {
  declare module.exports: any;
}

declare module 'deepcopy/src/index' {
  declare module.exports: any;
}

declare module 'deepcopy/src/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deepcopy/build/deepcopy.js' {
  declare module.exports: $Exports<'deepcopy/build/deepcopy'>;
}
declare module 'deepcopy/build/deepcopy.min.js' {
  declare module.exports: $Exports<'deepcopy/build/deepcopy.min'>;
}
declare module 'deepcopy/index' {
  declare module.exports: $Exports<'deepcopy'>;
}
declare module 'deepcopy/index.js' {
  declare module.exports: $Exports<'deepcopy'>;
}
declare module 'deepcopy/lib/copy.js' {
  declare module.exports: $Exports<'deepcopy/lib/copy'>;
}
declare module 'deepcopy/lib/index.js' {
  declare module.exports: $Exports<'deepcopy/lib/index'>;
}
declare module 'deepcopy/lib/polyfill.js' {
  declare module.exports: $Exports<'deepcopy/lib/polyfill'>;
}
declare module 'deepcopy/src/copy.js' {
  declare module.exports: $Exports<'deepcopy/src/copy'>;
}
declare module 'deepcopy/src/index.js' {
  declare module.exports: $Exports<'deepcopy/src/index'>;
}
declare module 'deepcopy/src/polyfill.js' {
  declare module.exports: $Exports<'deepcopy/src/polyfill'>;
}
