// flow-typed signature: 62bec543f0eb538a1b28ecbdc93514d5
// flow-typed version: <<STUB>>/discovery-swarm_v^4.4.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'discovery-swarm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'discovery-swarm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'discovery-swarm/example' {
  declare module.exports: any;
}

declare module 'discovery-swarm/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'discovery-swarm/example.js' {
  declare module.exports: $Exports<'discovery-swarm/example'>;
}
declare module 'discovery-swarm/index' {
  declare module.exports: $Exports<'discovery-swarm'>;
}
declare module 'discovery-swarm/index.js' {
  declare module.exports: $Exports<'discovery-swarm'>;
}
declare module 'discovery-swarm/test.js' {
  declare module.exports: $Exports<'discovery-swarm/test'>;
}
