// flow-typed signature: 25e1334880f64836de750e0b00be8f0a
// flow-typed version: <<STUB>>/ed25519-supercop_v^1.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ed25519-supercop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ed25519-supercop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ed25519-supercop/example/generate' {
  declare module.exports: any;
}

declare module 'ed25519-supercop/example/sign' {
  declare module.exports: any;
}

declare module 'ed25519-supercop/test/gen_sign_verify' {
  declare module.exports: any;
}

declare module 'ed25519-supercop/test/generate' {
  declare module.exports: any;
}

declare module 'ed25519-supercop/test/sign_and_verify' {
  declare module.exports: any;
}

declare module 'ed25519-supercop/test/sign_bep44' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ed25519-supercop/example/generate.js' {
  declare module.exports: $Exports<'ed25519-supercop/example/generate'>;
}
declare module 'ed25519-supercop/example/sign.js' {
  declare module.exports: $Exports<'ed25519-supercop/example/sign'>;
}
declare module 'ed25519-supercop/index' {
  declare module.exports: $Exports<'ed25519-supercop'>;
}
declare module 'ed25519-supercop/index.js' {
  declare module.exports: $Exports<'ed25519-supercop'>;
}
declare module 'ed25519-supercop/test/gen_sign_verify.js' {
  declare module.exports: $Exports<'ed25519-supercop/test/gen_sign_verify'>;
}
declare module 'ed25519-supercop/test/generate.js' {
  declare module.exports: $Exports<'ed25519-supercop/test/generate'>;
}
declare module 'ed25519-supercop/test/sign_and_verify.js' {
  declare module.exports: $Exports<'ed25519-supercop/test/sign_and_verify'>;
}
declare module 'ed25519-supercop/test/sign_bep44.js' {
  declare module.exports: $Exports<'ed25519-supercop/test/sign_bep44'>;
}
