// flow-typed signature: ca9d7c6116411601dad86d5e93636d1d
// flow-typed version: <<STUB>>/ed25519_v0.0.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ed25519'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ed25519' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ed25519/example' {
  declare module.exports: any;
}

declare module 'ed25519/test/ed25519' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ed25519/example.js' {
  declare module.exports: $Exports<'ed25519/example'>;
}
declare module 'ed25519/index' {
  declare module.exports: $Exports<'ed25519'>;
}
declare module 'ed25519/index.js' {
  declare module.exports: $Exports<'ed25519'>;
}
declare module 'ed25519/test/ed25519.js' {
  declare module.exports: $Exports<'ed25519/test/ed25519'>;
}
