// flow-typed signature: b7622c7b8b54a9efbab984f91d06082b
// flow-typed version: <<STUB>>/ethereumjs-block_v^1.7.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-block'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-block' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-block/from-rpc' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/header-from-rpc' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/header' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/karma.conf' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/tests/block' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/tests/difficulty' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/tests/from-rpc' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/tests/header' {
  declare module.exports: any;
}

declare module 'ethereumjs-block/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-block/from-rpc.js' {
  declare module.exports: $Exports<'ethereumjs-block/from-rpc'>;
}
declare module 'ethereumjs-block/header-from-rpc.js' {
  declare module.exports: $Exports<'ethereumjs-block/header-from-rpc'>;
}
declare module 'ethereumjs-block/header.js' {
  declare module.exports: $Exports<'ethereumjs-block/header'>;
}
declare module 'ethereumjs-block/index' {
  declare module.exports: $Exports<'ethereumjs-block'>;
}
declare module 'ethereumjs-block/index.js' {
  declare module.exports: $Exports<'ethereumjs-block'>;
}
declare module 'ethereumjs-block/karma.conf.js' {
  declare module.exports: $Exports<'ethereumjs-block/karma.conf'>;
}
declare module 'ethereumjs-block/tests/block.js' {
  declare module.exports: $Exports<'ethereumjs-block/tests/block'>;
}
declare module 'ethereumjs-block/tests/difficulty.js' {
  declare module.exports: $Exports<'ethereumjs-block/tests/difficulty'>;
}
declare module 'ethereumjs-block/tests/from-rpc.js' {
  declare module.exports: $Exports<'ethereumjs-block/tests/from-rpc'>;
}
declare module 'ethereumjs-block/tests/header.js' {
  declare module.exports: $Exports<'ethereumjs-block/tests/header'>;
}
declare module 'ethereumjs-block/tests/index.js' {
  declare module.exports: $Exports<'ethereumjs-block/tests/index'>;
}
