// flow-typed signature: 198882c8d93287892dc42009e8fdf388
// flow-typed version: <<STUB>>/ethereumjs-vm_v^2.3.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-vm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-vm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-vm/examples/run-blockchain/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/examples/run-transactions-complete/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/examples/run-transactions-complete/raw-tx2' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/examples/run-transactions-simple/bundle' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/examples/run-transactions-simple/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/examples/static-code-analysis' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/bloom' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/cache' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/exceptions' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/fakeBlockChain' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/hooked' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/logTable' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/opcodes' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/opFns' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/01-ecrecover' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/02-sha256' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/03-ripemd160' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/04-identity' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/05-modexp' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/06-ecadd' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/07-ecmul' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/precompiled/08-ecpairing' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runBlock' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runBlockchain' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runCall' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runCode' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runJit' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/runTx' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/lib/stateManager' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/BlockchainTestsRunner' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/cacheTest' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/GeneralStateTestsRunner' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/genesishashes' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/hooked' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/tester' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/util' {
  declare module.exports: any;
}

declare module 'ethereumjs-vm/tests/VMTestsRunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-vm/examples/run-blockchain/index.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/run-blockchain/index'>;
}
declare module 'ethereumjs-vm/examples/run-transactions-complete/index.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/run-transactions-complete/index'>;
}
declare module 'ethereumjs-vm/examples/run-transactions-complete/raw-tx2.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/run-transactions-complete/raw-tx2'>;
}
declare module 'ethereumjs-vm/examples/run-transactions-simple/bundle.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/run-transactions-simple/bundle'>;
}
declare module 'ethereumjs-vm/examples/run-transactions-simple/index.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/run-transactions-simple/index'>;
}
declare module 'ethereumjs-vm/examples/static-code-analysis.js' {
  declare module.exports: $Exports<'ethereumjs-vm/examples/static-code-analysis'>;
}
declare module 'ethereumjs-vm/index' {
  declare module.exports: $Exports<'ethereumjs-vm'>;
}
declare module 'ethereumjs-vm/index.js' {
  declare module.exports: $Exports<'ethereumjs-vm'>;
}
declare module 'ethereumjs-vm/lib/bloom.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/bloom'>;
}
declare module 'ethereumjs-vm/lib/cache.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/cache'>;
}
declare module 'ethereumjs-vm/lib/exceptions.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/exceptions'>;
}
declare module 'ethereumjs-vm/lib/fakeBlockChain.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/fakeBlockChain'>;
}
declare module 'ethereumjs-vm/lib/hooked.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/hooked'>;
}
declare module 'ethereumjs-vm/lib/index.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/index'>;
}
declare module 'ethereumjs-vm/lib/logTable.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/logTable'>;
}
declare module 'ethereumjs-vm/lib/opcodes.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/opcodes'>;
}
declare module 'ethereumjs-vm/lib/opFns.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/opFns'>;
}
declare module 'ethereumjs-vm/lib/precompiled/01-ecrecover.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/01-ecrecover'>;
}
declare module 'ethereumjs-vm/lib/precompiled/02-sha256.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/02-sha256'>;
}
declare module 'ethereumjs-vm/lib/precompiled/03-ripemd160.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/03-ripemd160'>;
}
declare module 'ethereumjs-vm/lib/precompiled/04-identity.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/04-identity'>;
}
declare module 'ethereumjs-vm/lib/precompiled/05-modexp.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/05-modexp'>;
}
declare module 'ethereumjs-vm/lib/precompiled/06-ecadd.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/06-ecadd'>;
}
declare module 'ethereumjs-vm/lib/precompiled/07-ecmul.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/07-ecmul'>;
}
declare module 'ethereumjs-vm/lib/precompiled/08-ecpairing.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/precompiled/08-ecpairing'>;
}
declare module 'ethereumjs-vm/lib/runBlock.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runBlock'>;
}
declare module 'ethereumjs-vm/lib/runBlockchain.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runBlockchain'>;
}
declare module 'ethereumjs-vm/lib/runCall.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runCall'>;
}
declare module 'ethereumjs-vm/lib/runCode.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runCode'>;
}
declare module 'ethereumjs-vm/lib/runJit.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runJit'>;
}
declare module 'ethereumjs-vm/lib/runTx.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/runTx'>;
}
declare module 'ethereumjs-vm/lib/stateManager.js' {
  declare module.exports: $Exports<'ethereumjs-vm/lib/stateManager'>;
}
declare module 'ethereumjs-vm/tests/BlockchainTestsRunner.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/BlockchainTestsRunner'>;
}
declare module 'ethereumjs-vm/tests/cacheTest.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/cacheTest'>;
}
declare module 'ethereumjs-vm/tests/GeneralStateTestsRunner.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/GeneralStateTestsRunner'>;
}
declare module 'ethereumjs-vm/tests/genesishashes.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/genesishashes'>;
}
declare module 'ethereumjs-vm/tests/hooked.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/hooked'>;
}
declare module 'ethereumjs-vm/tests/tester.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/tester'>;
}
declare module 'ethereumjs-vm/tests/util.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/util'>;
}
declare module 'ethereumjs-vm/tests/VMTestsRunner.js' {
  declare module.exports: $Exports<'ethereumjs-vm/tests/VMTestsRunner'>;
}
