// flow-typed signature: 348687e7c409d6dd2d197f22b9b531f9
// flow-typed version: <<STUB>>/express-winston_v2.5.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-winston/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-winston/index' {
  declare module.exports: $Exports<'express-winston'>;
}
declare module 'express-winston/index.js' {
  declare module.exports: $Exports<'express-winston'>;
}
declare module 'express-winston/test/test.js' {
  declare module.exports: $Exports<'express-winston/test/test'>;
}
