// flow-typed signature: 71fc6c32a8bd4a5d52ac1c834f2a47d0
// flow-typed version: <<STUB>>/getos_v^3.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getos/logic/alpine' {
  declare module.exports: any;
}

declare module 'getos/logic/amazon' {
  declare module.exports: any;
}

declare module 'getos/logic/centos' {
  declare module.exports: any;
}

declare module 'getos/logic/debian' {
  declare module.exports: any;
}

declare module 'getos/logic/fedora' {
  declare module.exports: any;
}

declare module 'getos/logic/raspbian' {
  declare module.exports: any;
}

declare module 'getos/logic/red' {
  declare module.exports: any;
}

declare module 'getos/logic/suse' {
  declare module.exports: any;
}

declare module 'getos/logic/ubuntu' {
  declare module.exports: any;
}

declare module 'getos/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getos/index' {
  declare module.exports: $Exports<'getos'>;
}
declare module 'getos/index.js' {
  declare module.exports: $Exports<'getos'>;
}
declare module 'getos/logic/alpine.js' {
  declare module.exports: $Exports<'getos/logic/alpine'>;
}
declare module 'getos/logic/amazon.js' {
  declare module.exports: $Exports<'getos/logic/amazon'>;
}
declare module 'getos/logic/centos.js' {
  declare module.exports: $Exports<'getos/logic/centos'>;
}
declare module 'getos/logic/debian.js' {
  declare module.exports: $Exports<'getos/logic/debian'>;
}
declare module 'getos/logic/fedora.js' {
  declare module.exports: $Exports<'getos/logic/fedora'>;
}
declare module 'getos/logic/raspbian.js' {
  declare module.exports: $Exports<'getos/logic/raspbian'>;
}
declare module 'getos/logic/red.js' {
  declare module.exports: $Exports<'getos/logic/red'>;
}
declare module 'getos/logic/suse.js' {
  declare module.exports: $Exports<'getos/logic/suse'>;
}
declare module 'getos/logic/ubuntu.js' {
  declare module.exports: $Exports<'getos/logic/ubuntu'>;
}
declare module 'getos/test.js' {
  declare module.exports: $Exports<'getos/test'>;
}
