// flow-typed signature: d17d9effc4ebc9101177702a7d24c897
// flow-typed version: <<STUB>>/gossipmonger-memory-storage_v^0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gossipmonger-memory-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gossipmonger-memory-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gossipmonger-memory-storage/scripts/test' {
  declare module.exports: any;
}

declare module 'gossipmonger-memory-storage/test/deadPeers' {
  declare module.exports: any;
}

declare module 'gossipmonger-memory-storage/test/livePeers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gossipmonger-memory-storage/index' {
  declare module.exports: $Exports<'gossipmonger-memory-storage'>;
}
declare module 'gossipmonger-memory-storage/index.js' {
  declare module.exports: $Exports<'gossipmonger-memory-storage'>;
}
declare module 'gossipmonger-memory-storage/scripts/test.js' {
  declare module.exports: $Exports<'gossipmonger-memory-storage/scripts/test'>;
}
declare module 'gossipmonger-memory-storage/test/deadPeers.js' {
  declare module.exports: $Exports<'gossipmonger-memory-storage/test/deadPeers'>;
}
declare module 'gossipmonger-memory-storage/test/livePeers.js' {
  declare module.exports: $Exports<'gossipmonger-memory-storage/test/livePeers'>;
}
