// flow-typed signature: ce9b74b74a645b183316516315e3114d
// flow-typed version: <<STUB>>/kad_v^2.5.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kad/example/expanded' {
  declare module.exports: any;
}

declare module 'kad/example/minimal' {
  declare module.exports: any;
}

declare module 'kad/lib/bucket' {
  declare module.exports: any;
}

declare module 'kad/lib/constants' {
  declare module.exports: any;
}

declare module 'kad/lib/contact-list' {
  declare module.exports: any;
}

declare module 'kad/lib/messenger' {
  declare module.exports: any;
}

declare module 'kad/lib/node-abstract' {
  declare module.exports: any;
}

declare module 'kad/lib/node-kademlia' {
  declare module.exports: any;
}

declare module 'kad/lib/routing-table' {
  declare module.exports: any;
}

declare module 'kad/lib/rules-errors' {
  declare module.exports: any;
}

declare module 'kad/lib/rules-kademlia' {
  declare module.exports: any;
}

declare module 'kad/lib/transport-http' {
  declare module.exports: any;
}

declare module 'kad/lib/transport-https' {
  declare module.exports: any;
}

declare module 'kad/lib/transport-udp' {
  declare module.exports: any;
}

declare module 'kad/lib/utils' {
  declare module.exports: any;
}

declare module 'kad/test/bucket.unit' {
  declare module.exports: any;
}

declare module 'kad/test/contact-list.unit' {
  declare module.exports: any;
}

declare module 'kad/test/fixtures/node-generator' {
  declare module.exports: any;
}

declare module 'kad/test/fixtures/transport-fake' {
  declare module.exports: any;
}

declare module 'kad/test/messenger.unit' {
  declare module.exports: any;
}

declare module 'kad/test/node-abstract.unit' {
  declare module.exports: any;
}

declare module 'kad/test/node-kademlia.e2e' {
  declare module.exports: any;
}

declare module 'kad/test/node-kademlia.unit' {
  declare module.exports: any;
}

declare module 'kad/test/node-kademlia+transport-http.integration' {
  declare module.exports: any;
}

declare module 'kad/test/node-kademlia+transport-udp.integration' {
  declare module.exports: any;
}

declare module 'kad/test/routing-table.unit' {
  declare module.exports: any;
}

declare module 'kad/test/rules-errors.unit' {
  declare module.exports: any;
}

declare module 'kad/test/rules-kademlia.unit' {
  declare module.exports: any;
}

declare module 'kad/test/transport-http.unit' {
  declare module.exports: any;
}

declare module 'kad/test/transport-https.unit' {
  declare module.exports: any;
}

declare module 'kad/test/transport-udp.unit' {
  declare module.exports: any;
}

declare module 'kad/test/utils.unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kad/example/expanded.js' {
  declare module.exports: $Exports<'kad/example/expanded'>;
}
declare module 'kad/example/minimal.js' {
  declare module.exports: $Exports<'kad/example/minimal'>;
}
declare module 'kad/index' {
  declare module.exports: $Exports<'kad'>;
}
declare module 'kad/index.js' {
  declare module.exports: $Exports<'kad'>;
}
declare module 'kad/lib/bucket.js' {
  declare module.exports: $Exports<'kad/lib/bucket'>;
}
declare module 'kad/lib/constants.js' {
  declare module.exports: $Exports<'kad/lib/constants'>;
}
declare module 'kad/lib/contact-list.js' {
  declare module.exports: $Exports<'kad/lib/contact-list'>;
}
declare module 'kad/lib/messenger.js' {
  declare module.exports: $Exports<'kad/lib/messenger'>;
}
declare module 'kad/lib/node-abstract.js' {
  declare module.exports: $Exports<'kad/lib/node-abstract'>;
}
declare module 'kad/lib/node-kademlia.js' {
  declare module.exports: $Exports<'kad/lib/node-kademlia'>;
}
declare module 'kad/lib/routing-table.js' {
  declare module.exports: $Exports<'kad/lib/routing-table'>;
}
declare module 'kad/lib/rules-errors.js' {
  declare module.exports: $Exports<'kad/lib/rules-errors'>;
}
declare module 'kad/lib/rules-kademlia.js' {
  declare module.exports: $Exports<'kad/lib/rules-kademlia'>;
}
declare module 'kad/lib/transport-http.js' {
  declare module.exports: $Exports<'kad/lib/transport-http'>;
}
declare module 'kad/lib/transport-https.js' {
  declare module.exports: $Exports<'kad/lib/transport-https'>;
}
declare module 'kad/lib/transport-udp.js' {
  declare module.exports: $Exports<'kad/lib/transport-udp'>;
}
declare module 'kad/lib/utils.js' {
  declare module.exports: $Exports<'kad/lib/utils'>;
}
declare module 'kad/test/bucket.unit.js' {
  declare module.exports: $Exports<'kad/test/bucket.unit'>;
}
declare module 'kad/test/contact-list.unit.js' {
  declare module.exports: $Exports<'kad/test/contact-list.unit'>;
}
declare module 'kad/test/fixtures/node-generator.js' {
  declare module.exports: $Exports<'kad/test/fixtures/node-generator'>;
}
declare module 'kad/test/fixtures/transport-fake.js' {
  declare module.exports: $Exports<'kad/test/fixtures/transport-fake'>;
}
declare module 'kad/test/messenger.unit.js' {
  declare module.exports: $Exports<'kad/test/messenger.unit'>;
}
declare module 'kad/test/node-abstract.unit.js' {
  declare module.exports: $Exports<'kad/test/node-abstract.unit'>;
}
declare module 'kad/test/node-kademlia.e2e.js' {
  declare module.exports: $Exports<'kad/test/node-kademlia.e2e'>;
}
declare module 'kad/test/node-kademlia.unit.js' {
  declare module.exports: $Exports<'kad/test/node-kademlia.unit'>;
}
declare module 'kad/test/node-kademlia+transport-http.integration.js' {
  declare module.exports: $Exports<'kad/test/node-kademlia+transport-http.integration'>;
}
declare module 'kad/test/node-kademlia+transport-udp.integration.js' {
  declare module.exports: $Exports<'kad/test/node-kademlia+transport-udp.integration'>;
}
declare module 'kad/test/routing-table.unit.js' {
  declare module.exports: $Exports<'kad/test/routing-table.unit'>;
}
declare module 'kad/test/rules-errors.unit.js' {
  declare module.exports: $Exports<'kad/test/rules-errors.unit'>;
}
declare module 'kad/test/rules-kademlia.unit.js' {
  declare module.exports: $Exports<'kad/test/rules-kademlia.unit'>;
}
declare module 'kad/test/transport-http.unit.js' {
  declare module.exports: $Exports<'kad/test/transport-http.unit'>;
}
declare module 'kad/test/transport-https.unit.js' {
  declare module.exports: $Exports<'kad/test/transport-https.unit'>;
}
declare module 'kad/test/transport-udp.unit.js' {
  declare module.exports: $Exports<'kad/test/transport-udp.unit'>;
}
declare module 'kad/test/utils.unit.js' {
  declare module.exports: $Exports<'kad/test/utils.unit'>;
}
