// flow-typed signature: fe280c569f5373d587d28bfa1c560ddf
// flow-typed version: <<STUB>>/levelup_v^2.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'levelup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'levelup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'levelup/buster' {
  declare module.exports: any;
}

declare module 'levelup/lib/batch' {
  declare module.exports: any;
}

declare module 'levelup/lib/levelup' {
  declare module.exports: any;
}

declare module 'levelup/lib/promisify' {
  declare module.exports: any;
}

declare module 'levelup/test/argument-checking-test' {
  declare module.exports: any;
}

declare module 'levelup/test/batch-test' {
  declare module.exports: any;
}

declare module 'levelup/test/binary-test' {
  declare module.exports: any;
}

declare module 'levelup/test/browserify-test' {
  declare module.exports: any;
}

declare module 'levelup/test/common' {
  declare module.exports: any;
}

declare module 'levelup/test/create-stream-vs-put-racecondition' {
  declare module.exports: any;
}

declare module 'levelup/test/data/browser-throws' {
  declare module.exports: any;
}

declare module 'levelup/test/data/browser-works' {
  declare module.exports: any;
}

declare module 'levelup/test/deferred-open-test' {
  declare module.exports: any;
}

declare module 'levelup/test/get-put-del-test' {
  declare module.exports: any;
}

declare module 'levelup/test/idempotent-test' {
  declare module.exports: any;
}

declare module 'levelup/test/index' {
  declare module.exports: any;
}

declare module 'levelup/test/init-test' {
  declare module.exports: any;
}

declare module 'levelup/test/inject-encoding-test' {
  declare module.exports: any;
}

declare module 'levelup/test/json-test' {
  declare module.exports: any;
}

declare module 'levelup/test/key-value-streams-test' {
  declare module.exports: any;
}

declare module 'levelup/test/leveldown-substitution-test' {
  declare module.exports: any;
}

declare module 'levelup/test/maybe-error-test' {
  declare module.exports: any;
}

declare module 'levelup/test/no-encoding-test' {
  declare module.exports: any;
}

declare module 'levelup/test/null-and-undefined-test' {
  declare module.exports: any;
}

declare module 'levelup/test/open-patchsafe-test' {
  declare module.exports: any;
}

declare module 'levelup/test/read-stream-test' {
  declare module.exports: any;
}

declare module 'levelup/test/snapshot-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'levelup/buster.js' {
  declare module.exports: $Exports<'levelup/buster'>;
}
declare module 'levelup/lib/batch.js' {
  declare module.exports: $Exports<'levelup/lib/batch'>;
}
declare module 'levelup/lib/levelup.js' {
  declare module.exports: $Exports<'levelup/lib/levelup'>;
}
declare module 'levelup/lib/promisify.js' {
  declare module.exports: $Exports<'levelup/lib/promisify'>;
}
declare module 'levelup/test/argument-checking-test.js' {
  declare module.exports: $Exports<'levelup/test/argument-checking-test'>;
}
declare module 'levelup/test/batch-test.js' {
  declare module.exports: $Exports<'levelup/test/batch-test'>;
}
declare module 'levelup/test/binary-test.js' {
  declare module.exports: $Exports<'levelup/test/binary-test'>;
}
declare module 'levelup/test/browserify-test.js' {
  declare module.exports: $Exports<'levelup/test/browserify-test'>;
}
declare module 'levelup/test/common.js' {
  declare module.exports: $Exports<'levelup/test/common'>;
}
declare module 'levelup/test/create-stream-vs-put-racecondition.js' {
  declare module.exports: $Exports<'levelup/test/create-stream-vs-put-racecondition'>;
}
declare module 'levelup/test/data/browser-throws.js' {
  declare module.exports: $Exports<'levelup/test/data/browser-throws'>;
}
declare module 'levelup/test/data/browser-works.js' {
  declare module.exports: $Exports<'levelup/test/data/browser-works'>;
}
declare module 'levelup/test/deferred-open-test.js' {
  declare module.exports: $Exports<'levelup/test/deferred-open-test'>;
}
declare module 'levelup/test/get-put-del-test.js' {
  declare module.exports: $Exports<'levelup/test/get-put-del-test'>;
}
declare module 'levelup/test/idempotent-test.js' {
  declare module.exports: $Exports<'levelup/test/idempotent-test'>;
}
declare module 'levelup/test/index.js' {
  declare module.exports: $Exports<'levelup/test/index'>;
}
declare module 'levelup/test/init-test.js' {
  declare module.exports: $Exports<'levelup/test/init-test'>;
}
declare module 'levelup/test/inject-encoding-test.js' {
  declare module.exports: $Exports<'levelup/test/inject-encoding-test'>;
}
declare module 'levelup/test/json-test.js' {
  declare module.exports: $Exports<'levelup/test/json-test'>;
}
declare module 'levelup/test/key-value-streams-test.js' {
  declare module.exports: $Exports<'levelup/test/key-value-streams-test'>;
}
declare module 'levelup/test/leveldown-substitution-test.js' {
  declare module.exports: $Exports<'levelup/test/leveldown-substitution-test'>;
}
declare module 'levelup/test/maybe-error-test.js' {
  declare module.exports: $Exports<'levelup/test/maybe-error-test'>;
}
declare module 'levelup/test/no-encoding-test.js' {
  declare module.exports: $Exports<'levelup/test/no-encoding-test'>;
}
declare module 'levelup/test/null-and-undefined-test.js' {
  declare module.exports: $Exports<'levelup/test/null-and-undefined-test'>;
}
declare module 'levelup/test/open-patchsafe-test.js' {
  declare module.exports: $Exports<'levelup/test/open-patchsafe-test'>;
}
declare module 'levelup/test/read-stream-test.js' {
  declare module.exports: $Exports<'levelup/test/read-stream-test'>;
}
declare module 'levelup/test/snapshot-test.js' {
  declare module.exports: $Exports<'levelup/test/snapshot-test'>;
}
