// flow-typed signature: c31c6eaf2228aa1fe986a08d2ec00f09
// flow-typed version: <<STUB>>/leveldown_v^3.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leveldown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leveldown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leveldown/chained-batch' {
  declare module.exports: any;
}

declare module 'leveldown/iterator' {
  declare module.exports: any;
}

declare module 'leveldown/leveldown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leveldown/chained-batch.js' {
  declare module.exports: $Exports<'leveldown/chained-batch'>;
}
declare module 'leveldown/iterator.js' {
  declare module.exports: $Exports<'leveldown/iterator'>;
}
declare module 'leveldown/leveldown.js' {
  declare module.exports: $Exports<'leveldown/leveldown'>;
}
