// flow-typed signature: b8db1159dad295bb793074dfb71dd973
// flow-typed version: <<STUB>>/libp2p_v^0.19.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libp2p'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libp2p' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libp2p/dist/index' {
  declare module.exports: any;
}

declare module 'libp2p/dist/index.min' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-c' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-c' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-d' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-e' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-c' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-d' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-e' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-1--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-1--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-2--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-2--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-3--peer-a' {
  declare module.exports: any;
}

declare module 'libp2p/pdd/pdd-transport--story-3--peer-b' {
  declare module.exports: any;
}

declare module 'libp2p/src/content-routing' {
  declare module.exports: any;
}

declare module 'libp2p/src/dht' {
  declare module.exports: any;
}

declare module 'libp2p/src/error-messages' {
  declare module.exports: any;
}

declare module 'libp2p/src/get-peer-info' {
  declare module.exports: any;
}

declare module 'libp2p/src/index' {
  declare module.exports: any;
}

declare module 'libp2p/src/peer-routing' {
  declare module.exports: any;
}

declare module 'libp2p/src/pubsub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libp2p/dist/index.js' {
  declare module.exports: $Exports<'libp2p/dist/index'>;
}
declare module 'libp2p/dist/index.min.js' {
  declare module.exports: $Exports<'libp2p/dist/index.min'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-a'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-1--peer-b'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-a'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-2--peer-b'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-a'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-b'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-c.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-3--peer-c'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-a'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-b'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-c.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-c'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-d.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-d'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-e.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-4--peer-e'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-a'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-b'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-c.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-c'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-d.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-d'>;
}
declare module 'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-e.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-the-ipfs-bundle--story-5--peer-e'>;
}
declare module 'libp2p/pdd/pdd-transport--story-1--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-1--peer-a'>;
}
declare module 'libp2p/pdd/pdd-transport--story-1--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-1--peer-b'>;
}
declare module 'libp2p/pdd/pdd-transport--story-2--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-2--peer-a'>;
}
declare module 'libp2p/pdd/pdd-transport--story-2--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-2--peer-b'>;
}
declare module 'libp2p/pdd/pdd-transport--story-3--peer-a.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-3--peer-a'>;
}
declare module 'libp2p/pdd/pdd-transport--story-3--peer-b.js' {
  declare module.exports: $Exports<'libp2p/pdd/pdd-transport--story-3--peer-b'>;
}
declare module 'libp2p/src/content-routing.js' {
  declare module.exports: $Exports<'libp2p/src/content-routing'>;
}
declare module 'libp2p/src/dht.js' {
  declare module.exports: $Exports<'libp2p/src/dht'>;
}
declare module 'libp2p/src/error-messages.js' {
  declare module.exports: $Exports<'libp2p/src/error-messages'>;
}
declare module 'libp2p/src/get-peer-info.js' {
  declare module.exports: $Exports<'libp2p/src/get-peer-info'>;
}
declare module 'libp2p/src/index.js' {
  declare module.exports: $Exports<'libp2p/src/index'>;
}
declare module 'libp2p/src/peer-routing.js' {
  declare module.exports: $Exports<'libp2p/src/peer-routing'>;
}
declare module 'libp2p/src/pubsub.js' {
  declare module.exports: $Exports<'libp2p/src/pubsub'>;
}
