// flow-typed signature: c3e84fcd504f6fa71a1bbed07f2ef6be
// flow-typed version: <<STUB>>/libp2p-railing_v^0.7.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libp2p-railing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libp2p-railing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libp2p-railing/examples/try' {
  declare module.exports: any;
}

declare module 'libp2p-railing/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libp2p-railing/examples/try.js' {
  declare module.exports: $Exports<'libp2p-railing/examples/try'>;
}
declare module 'libp2p-railing/src/index.js' {
  declare module.exports: $Exports<'libp2p-railing/src/index'>;
}
