// flow-typed signature: c34a1412cc67e894878e0c6787af9aba
// flow-typed version: <<STUB>>/libp2p-secio_v^0.9.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libp2p-secio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libp2p-secio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libp2p-secio/benchmarks/send' {
  declare module.exports: any;
}

declare module 'libp2p-secio/dist/index' {
  declare module.exports: any;
}

declare module 'libp2p-secio/dist/index.min' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/etm' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/crypto' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/exchange' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/finish' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/index' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/propose' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/handshake/secio.proto' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/index' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/state' {
  declare module.exports: any;
}

declare module 'libp2p-secio/src/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libp2p-secio/benchmarks/send.js' {
  declare module.exports: $Exports<'libp2p-secio/benchmarks/send'>;
}
declare module 'libp2p-secio/dist/index.js' {
  declare module.exports: $Exports<'libp2p-secio/dist/index'>;
}
declare module 'libp2p-secio/dist/index.min.js' {
  declare module.exports: $Exports<'libp2p-secio/dist/index.min'>;
}
declare module 'libp2p-secio/src/etm.js' {
  declare module.exports: $Exports<'libp2p-secio/src/etm'>;
}
declare module 'libp2p-secio/src/handshake/crypto.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/crypto'>;
}
declare module 'libp2p-secio/src/handshake/exchange.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/exchange'>;
}
declare module 'libp2p-secio/src/handshake/finish.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/finish'>;
}
declare module 'libp2p-secio/src/handshake/index.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/index'>;
}
declare module 'libp2p-secio/src/handshake/propose.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/propose'>;
}
declare module 'libp2p-secio/src/handshake/secio.proto.js' {
  declare module.exports: $Exports<'libp2p-secio/src/handshake/secio.proto'>;
}
declare module 'libp2p-secio/src/index.js' {
  declare module.exports: $Exports<'libp2p-secio/src/index'>;
}
declare module 'libp2p-secio/src/state.js' {
  declare module.exports: $Exports<'libp2p-secio/src/state'>;
}
declare module 'libp2p-secio/src/support.js' {
  declare module.exports: $Exports<'libp2p-secio/src/support'>;
}
