// flow-typed signature: 81d736a3b7ea10c26f05475f88578e81
// flow-typed version: <<STUB>>/mnemonist_v^0.21.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mnemonist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mnemonist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mnemonist/bi-map' {
  declare module.exports: any;
}

declare module 'mnemonist/bit-set' {
  declare module.exports: any;
}

declare module 'mnemonist/bit-vector' {
  declare module.exports: any;
}

declare module 'mnemonist/bk-tree' {
  declare module.exports: any;
}

declare module 'mnemonist/bloom-filter' {
  declare module.exports: any;
}

declare module 'mnemonist/circular-buffer' {
  declare module.exports: any;
}

declare module 'mnemonist/fibonacci-heap' {
  declare module.exports: any;
}

declare module 'mnemonist/finite-stack' {
  declare module.exports: any;
}

declare module 'mnemonist/fuzzy-map' {
  declare module.exports: any;
}

declare module 'mnemonist/fuzzy-multi-map' {
  declare module.exports: any;
}

declare module 'mnemonist/hashed-array-tree' {
  declare module.exports: any;
}

declare module 'mnemonist/heap' {
  declare module.exports: any;
}

declare module 'mnemonist/incremental-map' {
  declare module.exports: any;
}

declare module 'mnemonist/inverted-index' {
  declare module.exports: any;
}

declare module 'mnemonist/linked-list' {
  declare module.exports: any;
}

declare module 'mnemonist/multi-array' {
  declare module.exports: any;
}

declare module 'mnemonist/multi-map' {
  declare module.exports: any;
}

declare module 'mnemonist/multi-set' {
  declare module.exports: any;
}

declare module 'mnemonist/queue' {
  declare module.exports: any;
}

declare module 'mnemonist/semi-dynamic-trie' {
  declare module.exports: any;
}

declare module 'mnemonist/set' {
  declare module.exports: any;
}

declare module 'mnemonist/sparse-set' {
  declare module.exports: any;
}

declare module 'mnemonist/stack' {
  declare module.exports: any;
}

declare module 'mnemonist/static-disjoint-set' {
  declare module.exports: any;
}

declare module 'mnemonist/static-interval-tree' {
  declare module.exports: any;
}

declare module 'mnemonist/suffix-array' {
  declare module.exports: any;
}

declare module 'mnemonist/symspell' {
  declare module.exports: any;
}

declare module 'mnemonist/trie-map' {
  declare module.exports: any;
}

declare module 'mnemonist/trie' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/binary-search' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/bitwise' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/comparators' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/iterate' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/merge' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/murmurhash3' {
  declare module.exports: any;
}

declare module 'mnemonist/utils/typed-arrays' {
  declare module.exports: any;
}

declare module 'mnemonist/vector' {
  declare module.exports: any;
}

declare module 'mnemonist/vp-tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mnemonist/bi-map.js' {
  declare module.exports: $Exports<'mnemonist/bi-map'>;
}
declare module 'mnemonist/bit-set.js' {
  declare module.exports: $Exports<'mnemonist/bit-set'>;
}
declare module 'mnemonist/bit-vector.js' {
  declare module.exports: $Exports<'mnemonist/bit-vector'>;
}
declare module 'mnemonist/bk-tree.js' {
  declare module.exports: $Exports<'mnemonist/bk-tree'>;
}
declare module 'mnemonist/bloom-filter.js' {
  declare module.exports: $Exports<'mnemonist/bloom-filter'>;
}
declare module 'mnemonist/circular-buffer.js' {
  declare module.exports: $Exports<'mnemonist/circular-buffer'>;
}
declare module 'mnemonist/fibonacci-heap.js' {
  declare module.exports: $Exports<'mnemonist/fibonacci-heap'>;
}
declare module 'mnemonist/finite-stack.js' {
  declare module.exports: $Exports<'mnemonist/finite-stack'>;
}
declare module 'mnemonist/fuzzy-map.js' {
  declare module.exports: $Exports<'mnemonist/fuzzy-map'>;
}
declare module 'mnemonist/fuzzy-multi-map.js' {
  declare module.exports: $Exports<'mnemonist/fuzzy-multi-map'>;
}
declare module 'mnemonist/hashed-array-tree.js' {
  declare module.exports: $Exports<'mnemonist/hashed-array-tree'>;
}
declare module 'mnemonist/heap.js' {
  declare module.exports: $Exports<'mnemonist/heap'>;
}
declare module 'mnemonist/incremental-map.js' {
  declare module.exports: $Exports<'mnemonist/incremental-map'>;
}
declare module 'mnemonist/index' {
  declare module.exports: $Exports<'mnemonist'>;
}
declare module 'mnemonist/index.js' {
  declare module.exports: $Exports<'mnemonist'>;
}
declare module 'mnemonist/inverted-index.js' {
  declare module.exports: $Exports<'mnemonist/inverted-index'>;
}
declare module 'mnemonist/linked-list.js' {
  declare module.exports: $Exports<'mnemonist/linked-list'>;
}
declare module 'mnemonist/multi-array.js' {
  declare module.exports: $Exports<'mnemonist/multi-array'>;
}
declare module 'mnemonist/multi-map.js' {
  declare module.exports: $Exports<'mnemonist/multi-map'>;
}
declare module 'mnemonist/multi-set.js' {
  declare module.exports: $Exports<'mnemonist/multi-set'>;
}
declare module 'mnemonist/queue.js' {
  declare module.exports: $Exports<'mnemonist/queue'>;
}
declare module 'mnemonist/semi-dynamic-trie.js' {
  declare module.exports: $Exports<'mnemonist/semi-dynamic-trie'>;
}
declare module 'mnemonist/set.js' {
  declare module.exports: $Exports<'mnemonist/set'>;
}
declare module 'mnemonist/sparse-set.js' {
  declare module.exports: $Exports<'mnemonist/sparse-set'>;
}
declare module 'mnemonist/stack.js' {
  declare module.exports: $Exports<'mnemonist/stack'>;
}
declare module 'mnemonist/static-disjoint-set.js' {
  declare module.exports: $Exports<'mnemonist/static-disjoint-set'>;
}
declare module 'mnemonist/static-interval-tree.js' {
  declare module.exports: $Exports<'mnemonist/static-interval-tree'>;
}
declare module 'mnemonist/suffix-array.js' {
  declare module.exports: $Exports<'mnemonist/suffix-array'>;
}
declare module 'mnemonist/symspell.js' {
  declare module.exports: $Exports<'mnemonist/symspell'>;
}
declare module 'mnemonist/trie-map.js' {
  declare module.exports: $Exports<'mnemonist/trie-map'>;
}
declare module 'mnemonist/trie.js' {
  declare module.exports: $Exports<'mnemonist/trie'>;
}
declare module 'mnemonist/utils/binary-search.js' {
  declare module.exports: $Exports<'mnemonist/utils/binary-search'>;
}
declare module 'mnemonist/utils/bitwise.js' {
  declare module.exports: $Exports<'mnemonist/utils/bitwise'>;
}
declare module 'mnemonist/utils/comparators.js' {
  declare module.exports: $Exports<'mnemonist/utils/comparators'>;
}
declare module 'mnemonist/utils/iterate.js' {
  declare module.exports: $Exports<'mnemonist/utils/iterate'>;
}
declare module 'mnemonist/utils/merge.js' {
  declare module.exports: $Exports<'mnemonist/utils/merge'>;
}
declare module 'mnemonist/utils/murmurhash3.js' {
  declare module.exports: $Exports<'mnemonist/utils/murmurhash3'>;
}
declare module 'mnemonist/utils/typed-arrays.js' {
  declare module.exports: $Exports<'mnemonist/utils/typed-arrays'>;
}
declare module 'mnemonist/vector.js' {
  declare module.exports: $Exports<'mnemonist/vector'>;
}
declare module 'mnemonist/vp-tree.js' {
  declare module.exports: $Exports<'mnemonist/vp-tree'>;
}
