// flow-typed signature: ec8f887a480b3de59a37f15725f3618f
// flow-typed version: <<STUB>>/n64_v^0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'n64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'n64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'n64/lib/n64' {
  declare module.exports: any;
}

declare module 'n64/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'n64/lib/n64.js' {
  declare module.exports: $Exports<'n64/lib/n64'>;
}
declare module 'n64/webpack.config.js' {
  declare module.exports: $Exports<'n64/webpack.config'>;
}
