// flow-typed signature: fc9dc1ea255f090a898e6b0c710c072e
// flow-typed version: <<STUB>>/nsp_v3.2.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nsp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nsp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nsp/commands/check' {
  declare module.exports: any;
}

declare module 'nsp/commands/gather' {
  declare module.exports: any;
}

declare module 'nsp/commands/login' {
  declare module.exports: any;
}

declare module 'nsp/lib/api' {
  declare module.exports: any;
}

declare module 'nsp/lib/command' {
  declare module.exports: any;
}

declare module 'nsp/lib/config' {
  declare module.exports: any;
}

declare module 'nsp/lib/index' {
  declare module.exports: any;
}

declare module 'nsp/lib/offline' {
  declare module.exports: any;
}

declare module 'nsp/lib/package' {
  declare module.exports: any;
}

declare module 'nsp/lib/preprocessor' {
  declare module.exports: any;
}

declare module 'nsp/lib/wreck' {
  declare module.exports: any;
}

declare module 'nsp/reporters/codeclimate' {
  declare module.exports: any;
}

declare module 'nsp/reporters/index' {
  declare module.exports: any;
}

declare module 'nsp/reporters/json' {
  declare module.exports: any;
}

declare module 'nsp/reporters/minimal' {
  declare module.exports: any;
}

declare module 'nsp/reporters/summary' {
  declare module.exports: any;
}

declare module 'nsp/reporters/table' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nsp/commands/check.js' {
  declare module.exports: $Exports<'nsp/commands/check'>;
}
declare module 'nsp/commands/gather.js' {
  declare module.exports: $Exports<'nsp/commands/gather'>;
}
declare module 'nsp/commands/login.js' {
  declare module.exports: $Exports<'nsp/commands/login'>;
}
declare module 'nsp/lib/api.js' {
  declare module.exports: $Exports<'nsp/lib/api'>;
}
declare module 'nsp/lib/command.js' {
  declare module.exports: $Exports<'nsp/lib/command'>;
}
declare module 'nsp/lib/config.js' {
  declare module.exports: $Exports<'nsp/lib/config'>;
}
declare module 'nsp/lib/index.js' {
  declare module.exports: $Exports<'nsp/lib/index'>;
}
declare module 'nsp/lib/offline.js' {
  declare module.exports: $Exports<'nsp/lib/offline'>;
}
declare module 'nsp/lib/package.js' {
  declare module.exports: $Exports<'nsp/lib/package'>;
}
declare module 'nsp/lib/preprocessor.js' {
  declare module.exports: $Exports<'nsp/lib/preprocessor'>;
}
declare module 'nsp/lib/wreck.js' {
  declare module.exports: $Exports<'nsp/lib/wreck'>;
}
declare module 'nsp/reporters/codeclimate.js' {
  declare module.exports: $Exports<'nsp/reporters/codeclimate'>;
}
declare module 'nsp/reporters/index.js' {
  declare module.exports: $Exports<'nsp/reporters/index'>;
}
declare module 'nsp/reporters/json.js' {
  declare module.exports: $Exports<'nsp/reporters/json'>;
}
declare module 'nsp/reporters/minimal.js' {
  declare module.exports: $Exports<'nsp/reporters/minimal'>;
}
declare module 'nsp/reporters/summary.js' {
  declare module.exports: $Exports<'nsp/reporters/summary'>;
}
declare module 'nsp/reporters/table.js' {
  declare module.exports: $Exports<'nsp/reporters/table'>;
}
