// flow-typed signature: 6e41f66d0728d6bb9f785981c00f58a1
// flow-typed version: <<STUB>>/portscanner_v^2.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'portscanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'portscanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'portscanner/lib/portscanner' {
  declare module.exports: any;
}

declare module 'portscanner/lib/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'portscanner/lib/portscanner.js' {
  declare module.exports: $Exports<'portscanner/lib/portscanner'>;
}
declare module 'portscanner/lib/promisify.js' {
  declare module.exports: $Exports<'portscanner/lib/promisify'>;
}
