// flow-typed signature: 3484a3d61179d0bd525827c4a823eda1
// flow-typed version: <<STUB>>/serve-index_v^1.9.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve-index'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve-index' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serve-index/index' {
  declare module.exports: $Exports<'serve-index'>;
}
declare module 'serve-index/index.js' {
  declare module.exports: $Exports<'serve-index'>;
}
