// flow-typed signature: 3408979c74fbd3538660fa000a8fa3c5
// flow-typed version: <<STUB>>/waves-api_v^0.24.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'waves-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'waves-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'waves-api/dist/waves-api' {
  declare module.exports: any;
}

declare module 'waves-api/dist/waves-api.min' {
  declare module.exports: any;
}

declare module 'waves-api/dist/waves-api.partial' {
  declare module.exports: any;
}

declare module 'waves-api/dist/waves-api.partial.min' {
  declare module.exports: any;
}

declare module 'waves-api/karma.conf' {
  declare module.exports: any;
}

declare module 'waves-api/karma.test' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/index' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/ArrayPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/BasePart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/BooleanPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/config' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/DatePart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/NumberPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/ObjectPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/Schema' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/StringDatePart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-api-validator/src/StringPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/index' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/filters' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/Iterator' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/Path' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/Receiver' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/Signal' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/tree/BaseTree' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/tree/Tree' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/utils' {
  declare module.exports: any;
}

declare module 'waves-api/raw/node_modules/ts-utils/src/utilsWithFilters' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/matcher/index' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/matcher/v1/info' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/matcher/v1/orderbooks' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/matcher/v1/orderbooks.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/index' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/addresses' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/aliases' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/aliases.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/assets' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/assets.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/blocks' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/leasing' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/leasing.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v1/transactions' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/_combiners' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/_filters' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/_warn' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/addresses' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/addresses.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/aliases' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/aliases.x' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/node/v2/transactions' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schema.Base58Part' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schema.MoneyPart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schema.OrderPricePart' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schema.transactions' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schemaFields' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schemaTemporaryTools' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/api/schemaTools' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/Asset' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/AssetPair' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/ByteProcessor' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/Money' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/OrderPrice' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/Seed' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/classes/Transactions' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/config' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/constants' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/errors/WavesError' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/errors/WavesRequestError' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/axlsign' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/base58' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/bignumber' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/blake2b' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/converters' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/fetch' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/secure-random' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/libs/sha3' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/seedDictionary' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/tools' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/concat' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/convert' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/crypto' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/logger' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/remap' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/request' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/utils/storage' {
  declare module.exports: any;
}

declare module 'waves-api/raw/src/WavesAPI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'waves-api/dist/waves-api.js' {
  declare module.exports: $Exports<'waves-api/dist/waves-api'>;
}
declare module 'waves-api/dist/waves-api.min.js' {
  declare module.exports: $Exports<'waves-api/dist/waves-api.min'>;
}
declare module 'waves-api/dist/waves-api.partial.js' {
  declare module.exports: $Exports<'waves-api/dist/waves-api.partial'>;
}
declare module 'waves-api/dist/waves-api.partial.min.js' {
  declare module.exports: $Exports<'waves-api/dist/waves-api.partial.min'>;
}
declare module 'waves-api/karma.conf.js' {
  declare module.exports: $Exports<'waves-api/karma.conf'>;
}
declare module 'waves-api/karma.test.js' {
  declare module.exports: $Exports<'waves-api/karma.test'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/index.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/index'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/ArrayPart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/ArrayPart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/BasePart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/BasePart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/BooleanPart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/BooleanPart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/config.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/config'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/DatePart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/DatePart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/NumberPart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/NumberPart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/ObjectPart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/ObjectPart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/Schema.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/Schema'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/StringDatePart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/StringDatePart'>;
}
declare module 'waves-api/raw/node_modules/ts-api-validator/src/StringPart.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-api-validator/src/StringPart'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/index.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/index'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/filters.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/filters'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/Iterator.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/Iterator'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/Path.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/Path'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/Receiver.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/Receiver'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/Signal.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/Signal'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/tree/BaseTree.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/tree/BaseTree'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/tree/Tree.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/tree/Tree'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/utils.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/utils'>;
}
declare module 'waves-api/raw/node_modules/ts-utils/src/utilsWithFilters.js' {
  declare module.exports: $Exports<'waves-api/raw/node_modules/ts-utils/src/utilsWithFilters'>;
}
declare module 'waves-api/raw/src/api/matcher/index.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/matcher/index'>;
}
declare module 'waves-api/raw/src/api/matcher/v1/info.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/matcher/v1/info'>;
}
declare module 'waves-api/raw/src/api/matcher/v1/orderbooks.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/matcher/v1/orderbooks'>;
}
declare module 'waves-api/raw/src/api/matcher/v1/orderbooks.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/matcher/v1/orderbooks.x'>;
}
declare module 'waves-api/raw/src/api/node/index.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/index'>;
}
declare module 'waves-api/raw/src/api/node/v1/addresses.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/addresses'>;
}
declare module 'waves-api/raw/src/api/node/v1/aliases.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/aliases'>;
}
declare module 'waves-api/raw/src/api/node/v1/aliases.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/aliases.x'>;
}
declare module 'waves-api/raw/src/api/node/v1/assets.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/assets'>;
}
declare module 'waves-api/raw/src/api/node/v1/assets.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/assets.x'>;
}
declare module 'waves-api/raw/src/api/node/v1/blocks.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/blocks'>;
}
declare module 'waves-api/raw/src/api/node/v1/leasing.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/leasing'>;
}
declare module 'waves-api/raw/src/api/node/v1/leasing.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/leasing.x'>;
}
declare module 'waves-api/raw/src/api/node/v1/transactions.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v1/transactions'>;
}
declare module 'waves-api/raw/src/api/node/v2/_combiners.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/_combiners'>;
}
declare module 'waves-api/raw/src/api/node/v2/_filters.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/_filters'>;
}
declare module 'waves-api/raw/src/api/node/v2/_warn.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/_warn'>;
}
declare module 'waves-api/raw/src/api/node/v2/addresses.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/addresses'>;
}
declare module 'waves-api/raw/src/api/node/v2/addresses.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/addresses.x'>;
}
declare module 'waves-api/raw/src/api/node/v2/aliases.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/aliases'>;
}
declare module 'waves-api/raw/src/api/node/v2/aliases.x.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/aliases.x'>;
}
declare module 'waves-api/raw/src/api/node/v2/transactions.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/node/v2/transactions'>;
}
declare module 'waves-api/raw/src/api/schema.Base58Part.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schema.Base58Part'>;
}
declare module 'waves-api/raw/src/api/schema.MoneyPart.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schema.MoneyPart'>;
}
declare module 'waves-api/raw/src/api/schema.OrderPricePart.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schema.OrderPricePart'>;
}
declare module 'waves-api/raw/src/api/schema.transactions.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schema.transactions'>;
}
declare module 'waves-api/raw/src/api/schemaFields.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schemaFields'>;
}
declare module 'waves-api/raw/src/api/schemaTemporaryTools.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schemaTemporaryTools'>;
}
declare module 'waves-api/raw/src/api/schemaTools.js' {
  declare module.exports: $Exports<'waves-api/raw/src/api/schemaTools'>;
}
declare module 'waves-api/raw/src/classes/Asset.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/Asset'>;
}
declare module 'waves-api/raw/src/classes/AssetPair.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/AssetPair'>;
}
declare module 'waves-api/raw/src/classes/ByteProcessor.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/ByteProcessor'>;
}
declare module 'waves-api/raw/src/classes/Money.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/Money'>;
}
declare module 'waves-api/raw/src/classes/OrderPrice.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/OrderPrice'>;
}
declare module 'waves-api/raw/src/classes/Seed.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/Seed'>;
}
declare module 'waves-api/raw/src/classes/Transactions.js' {
  declare module.exports: $Exports<'waves-api/raw/src/classes/Transactions'>;
}
declare module 'waves-api/raw/src/config.js' {
  declare module.exports: $Exports<'waves-api/raw/src/config'>;
}
declare module 'waves-api/raw/src/constants.js' {
  declare module.exports: $Exports<'waves-api/raw/src/constants'>;
}
declare module 'waves-api/raw/src/errors/WavesError.js' {
  declare module.exports: $Exports<'waves-api/raw/src/errors/WavesError'>;
}
declare module 'waves-api/raw/src/errors/WavesRequestError.js' {
  declare module.exports: $Exports<'waves-api/raw/src/errors/WavesRequestError'>;
}
declare module 'waves-api/raw/src/libs/axlsign.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/axlsign'>;
}
declare module 'waves-api/raw/src/libs/base58.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/base58'>;
}
declare module 'waves-api/raw/src/libs/bignumber.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/bignumber'>;
}
declare module 'waves-api/raw/src/libs/blake2b.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/blake2b'>;
}
declare module 'waves-api/raw/src/libs/converters.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/converters'>;
}
declare module 'waves-api/raw/src/libs/fetch.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/fetch'>;
}
declare module 'waves-api/raw/src/libs/secure-random.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/secure-random'>;
}
declare module 'waves-api/raw/src/libs/sha3.js' {
  declare module.exports: $Exports<'waves-api/raw/src/libs/sha3'>;
}
declare module 'waves-api/raw/src/seedDictionary.js' {
  declare module.exports: $Exports<'waves-api/raw/src/seedDictionary'>;
}
declare module 'waves-api/raw/src/tools.js' {
  declare module.exports: $Exports<'waves-api/raw/src/tools'>;
}
declare module 'waves-api/raw/src/utils/concat.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/concat'>;
}
declare module 'waves-api/raw/src/utils/convert.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/convert'>;
}
declare module 'waves-api/raw/src/utils/crypto.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/crypto'>;
}
declare module 'waves-api/raw/src/utils/logger.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/logger'>;
}
declare module 'waves-api/raw/src/utils/remap.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/remap'>;
}
declare module 'waves-api/raw/src/utils/request.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/request'>;
}
declare module 'waves-api/raw/src/utils/storage.js' {
  declare module.exports: $Exports<'waves-api/raw/src/utils/storage'>;
}
declare module 'waves-api/raw/src/WavesAPI.js' {
  declare module.exports: $Exports<'waves-api/raw/src/WavesAPI'>;
}
