// flow-typed signature: f1c18b99b1fd9220df2871ad94c3dcb2
// flow-typed version: <<STUB>>/webcoin-bitcoin_v^3.1.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webcoin-bitcoin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webcoin-bitcoin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webcoin-bitcoin/lib/blockchain' {
  declare module.exports: any;
}

declare module 'webcoin-bitcoin/lib/net' {
  declare module.exports: any;
}

declare module 'webcoin-bitcoin/lib/versionbits' {
  declare module.exports: any;
}

declare module 'webcoin-bitcoin/lib/wallet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webcoin-bitcoin/index' {
  declare module.exports: $Exports<'webcoin-bitcoin'>;
}
declare module 'webcoin-bitcoin/index.js' {
  declare module.exports: $Exports<'webcoin-bitcoin'>;
}
declare module 'webcoin-bitcoin/lib/blockchain.js' {
  declare module.exports: $Exports<'webcoin-bitcoin/lib/blockchain'>;
}
declare module 'webcoin-bitcoin/lib/net.js' {
  declare module.exports: $Exports<'webcoin-bitcoin/lib/net'>;
}
declare module 'webcoin-bitcoin/lib/versionbits.js' {
  declare module.exports: $Exports<'webcoin-bitcoin/lib/versionbits'>;
}
declare module 'webcoin-bitcoin/lib/wallet.js' {
  declare module.exports: $Exports<'webcoin-bitcoin/lib/wallet'>;
}
