// flow-typed signature: c22fd0df45dae9f0a0577b46bbfa002b
// flow-typed version: <<STUB>>/xor-it_v^1.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xor-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xor-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xor-it/dist/xorIt' {
  declare module.exports: any;
}

declare module 'xor-it/example' {
  declare module.exports: any;
}

declare module 'xor-it/src/xorIt' {
  declare module.exports: any;
}

declare module 'xor-it/test-dist/xorIt-tests' {
  declare module.exports: any;
}

declare module 'xor-it/test/xorIt-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xor-it/dist/xorIt.js' {
  declare module.exports: $Exports<'xor-it/dist/xorIt'>;
}
declare module 'xor-it/example.js' {
  declare module.exports: $Exports<'xor-it/example'>;
}
declare module 'xor-it/src/xorIt.js' {
  declare module.exports: $Exports<'xor-it/src/xorIt'>;
}
declare module 'xor-it/test-dist/xorIt-tests.js' {
  declare module.exports: $Exports<'xor-it/test-dist/xorIt-tests'>;
}
declare module 'xor-it/test/xorIt-tests.js' {
  declare module.exports: $Exports<'xor-it/test/xorIt-tests'>;
}
