/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.bc.BcBlock', null, global);
goog.exportSymbol('proto.bc.BcTransaction', null, global);
goog.exportSymbol('proto.bc.Block', null, global);
goog.exportSymbol('proto.bc.BlockchainHeader', null, global);
goog.exportSymbol('proto.bc.BlockchainHeaders', null, global);
goog.exportSymbol('proto.bc.Null', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.Null = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.Null, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.Null.displayName = 'proto.bc.Null';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.Null.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.Null.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.Null} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Null.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.Null}
 */
proto.bc.Null.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.Null;
  return proto.bc.Null.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.Null} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.Null}
 */
proto.bc.Null.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.Null.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.Null.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.Null} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Null.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.Block = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.Block, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.Block.displayName = 'proto.bc.Block';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.Block.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.Block.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.Block} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Block.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockchain: jspb.Message.getFieldWithDefault(msg, 1, ""),
    hash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    previousHash: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    height: jspb.Message.getFieldWithDefault(msg, 5, 0),
    merkleRoot: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.Block}
 */
proto.bc.Block.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.Block;
  return proto.bc.Block.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.Block} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.Block}
 */
proto.bc.Block.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockchain(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHeight(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMerkleRoot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.Block.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.Block.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.Block} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.Block.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlockchain();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPreviousHash();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getMerkleRoot();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string blockchain = 1;
 * @return {string}
 */
proto.bc.Block.prototype.getBlockchain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.Block.prototype.setBlockchain = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string hash = 2;
 * @return {string}
 */
proto.bc.Block.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bc.Block.prototype.setHash = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string previous_hash = 3;
 * @return {string}
 */
proto.bc.Block.prototype.getPreviousHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.bc.Block.prototype.setPreviousHash = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint64 timestamp = 4;
 * @return {number}
 */
proto.bc.Block.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bc.Block.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint64 height = 5;
 * @return {number}
 */
proto.bc.Block.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.bc.Block.prototype.setHeight = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string merkle_root = 6;
 * @return {string}
 */
proto.bc.Block.prototype.getMerkleRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.bc.Block.prototype.setMerkleRoot = function(value) {
  jspb.Message.setField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.BlockchainHeaders = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.BlockchainHeaders.repeatedFields_, null);
};
goog.inherits(proto.bc.BlockchainHeaders, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.BlockchainHeaders.displayName = 'proto.bc.BlockchainHeaders';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.BlockchainHeaders.repeatedFields_ = [1,2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.BlockchainHeaders.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.BlockchainHeaders.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.BlockchainHeaders} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BlockchainHeaders.toObject = function(includeInstance, msg) {
  var f, obj = {
    btcList: jspb.Message.toObjectList(msg.getBtcList(),
    proto.bc.BlockchainHeader.toObject, includeInstance),
    ethList: jspb.Message.toObjectList(msg.getEthList(),
    proto.bc.BlockchainHeader.toObject, includeInstance),
    lskList: jspb.Message.toObjectList(msg.getLskList(),
    proto.bc.BlockchainHeader.toObject, includeInstance),
    neoList: jspb.Message.toObjectList(msg.getNeoList(),
    proto.bc.BlockchainHeader.toObject, includeInstance),
    wavList: jspb.Message.toObjectList(msg.getWavList(),
    proto.bc.BlockchainHeader.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.BlockchainHeaders}
 */
proto.bc.BlockchainHeaders.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.BlockchainHeaders;
  return proto.bc.BlockchainHeaders.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.BlockchainHeaders} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.BlockchainHeaders}
 */
proto.bc.BlockchainHeaders.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bc.BlockchainHeader;
      reader.readMessage(value,proto.bc.BlockchainHeader.deserializeBinaryFromReader);
      msg.addBtc(value);
      break;
    case 2:
      var value = new proto.bc.BlockchainHeader;
      reader.readMessage(value,proto.bc.BlockchainHeader.deserializeBinaryFromReader);
      msg.addEth(value);
      break;
    case 3:
      var value = new proto.bc.BlockchainHeader;
      reader.readMessage(value,proto.bc.BlockchainHeader.deserializeBinaryFromReader);
      msg.addLsk(value);
      break;
    case 4:
      var value = new proto.bc.BlockchainHeader;
      reader.readMessage(value,proto.bc.BlockchainHeader.deserializeBinaryFromReader);
      msg.addNeo(value);
      break;
    case 5:
      var value = new proto.bc.BlockchainHeader;
      reader.readMessage(value,proto.bc.BlockchainHeader.deserializeBinaryFromReader);
      msg.addWav(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.BlockchainHeaders.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.BlockchainHeaders.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.BlockchainHeaders} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BlockchainHeaders.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBtcList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bc.BlockchainHeader.serializeBinaryToWriter
    );
  }
  f = message.getEthList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.bc.BlockchainHeader.serializeBinaryToWriter
    );
  }
  f = message.getLskList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.bc.BlockchainHeader.serializeBinaryToWriter
    );
  }
  f = message.getNeoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.bc.BlockchainHeader.serializeBinaryToWriter
    );
  }
  f = message.getWavList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.bc.BlockchainHeader.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BlockchainHeader btc = 1;
 * @return {!Array.<!proto.bc.BlockchainHeader>}
 */
proto.bc.BlockchainHeaders.prototype.getBtcList = function() {
  return /** @type{!Array.<!proto.bc.BlockchainHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BlockchainHeader, 1));
};


/** @param {!Array.<!proto.bc.BlockchainHeader>} value */
proto.bc.BlockchainHeaders.prototype.setBtcList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bc.BlockchainHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeaders.prototype.addBtc = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bc.BlockchainHeader, opt_index);
};


proto.bc.BlockchainHeaders.prototype.clearBtcList = function() {
  this.setBtcList([]);
};


/**
 * repeated BlockchainHeader eth = 2;
 * @return {!Array.<!proto.bc.BlockchainHeader>}
 */
proto.bc.BlockchainHeaders.prototype.getEthList = function() {
  return /** @type{!Array.<!proto.bc.BlockchainHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BlockchainHeader, 2));
};


/** @param {!Array.<!proto.bc.BlockchainHeader>} value */
proto.bc.BlockchainHeaders.prototype.setEthList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bc.BlockchainHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeaders.prototype.addEth = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bc.BlockchainHeader, opt_index);
};


proto.bc.BlockchainHeaders.prototype.clearEthList = function() {
  this.setEthList([]);
};


/**
 * repeated BlockchainHeader lsk = 3;
 * @return {!Array.<!proto.bc.BlockchainHeader>}
 */
proto.bc.BlockchainHeaders.prototype.getLskList = function() {
  return /** @type{!Array.<!proto.bc.BlockchainHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BlockchainHeader, 3));
};


/** @param {!Array.<!proto.bc.BlockchainHeader>} value */
proto.bc.BlockchainHeaders.prototype.setLskList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.bc.BlockchainHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeaders.prototype.addLsk = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.bc.BlockchainHeader, opt_index);
};


proto.bc.BlockchainHeaders.prototype.clearLskList = function() {
  this.setLskList([]);
};


/**
 * repeated BlockchainHeader neo = 4;
 * @return {!Array.<!proto.bc.BlockchainHeader>}
 */
proto.bc.BlockchainHeaders.prototype.getNeoList = function() {
  return /** @type{!Array.<!proto.bc.BlockchainHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BlockchainHeader, 4));
};


/** @param {!Array.<!proto.bc.BlockchainHeader>} value */
proto.bc.BlockchainHeaders.prototype.setNeoList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.bc.BlockchainHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeaders.prototype.addNeo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.bc.BlockchainHeader, opt_index);
};


proto.bc.BlockchainHeaders.prototype.clearNeoList = function() {
  this.setNeoList([]);
};


/**
 * repeated BlockchainHeader wav = 5;
 * @return {!Array.<!proto.bc.BlockchainHeader>}
 */
proto.bc.BlockchainHeaders.prototype.getWavList = function() {
  return /** @type{!Array.<!proto.bc.BlockchainHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BlockchainHeader, 5));
};


/** @param {!Array.<!proto.bc.BlockchainHeader>} value */
proto.bc.BlockchainHeaders.prototype.setWavList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.bc.BlockchainHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeaders.prototype.addWav = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.bc.BlockchainHeader, opt_index);
};


proto.bc.BlockchainHeaders.prototype.clearWavList = function() {
  this.setWavList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.BcBlock = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bc.BcBlock.repeatedFields_, null);
};
goog.inherits(proto.bc.BcBlock, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.BcBlock.displayName = 'proto.bc.BcBlock';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bc.BcBlock.repeatedFields_ = [20,26];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.BcBlock.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.BcBlock.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.BcBlock} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BcBlock.toObject = function(includeInstance, msg) {
  var f, obj = {
    hash: jspb.Message.getFieldWithDefault(msg, 1, ""),
    previousHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    version: jspb.Message.getFieldWithDefault(msg, 3, 0),
    schemaVersion: jspb.Message.getFieldWithDefault(msg, 4, 0),
    height: jspb.Message.getFieldWithDefault(msg, 5, 0),
    miner: jspb.Message.getFieldWithDefault(msg, 6, ""),
    difficulty: +jspb.Message.getFieldWithDefault(msg, 7, 0.0),
    timestamp: jspb.Message.getFieldWithDefault(msg, 8, 0),
    merkleRoot: jspb.Message.getFieldWithDefault(msg, 9, ""),
    chainRoot: jspb.Message.getFieldWithDefault(msg, 10, ""),
    distance: jspb.Message.getFieldWithDefault(msg, 11, 0),
    totalDistance: jspb.Message.getFieldWithDefault(msg, 12, 0),
    nonce: jspb.Message.getFieldWithDefault(msg, 13, ""),
    nrgGrant: jspb.Message.getFieldWithDefault(msg, 14, 0),
    targetHash: jspb.Message.getFieldWithDefault(msg, 15, ""),
    targetHeight: jspb.Message.getFieldWithDefault(msg, 16, 0),
    targetMiner: jspb.Message.getFieldWithDefault(msg, 17, ""),
    targetSignature: jspb.Message.getFieldWithDefault(msg, 18, ""),
    twn: jspb.Message.getFieldWithDefault(msg, 19, 0),
    twsList: jspb.Message.getRepeatedField(msg, 20),
    emblemWeight: jspb.Message.getFieldWithDefault(msg, 21, 0),
    emblemChainBlockHash: jspb.Message.getFieldWithDefault(msg, 22, ""),
    emblemChainFingerprintRoot: jspb.Message.getFieldWithDefault(msg, 23, ""),
    emblemChainAddress: jspb.Message.getFieldWithDefault(msg, 24, ""),
    txCount: jspb.Message.getFieldWithDefault(msg, 25, 0),
    txsList: jspb.Message.toObjectList(msg.getTxsList(),
    proto.bc.BcTransaction.toObject, includeInstance),
    txFeeBase: jspb.Message.getFieldWithDefault(msg, 27, 0),
    txDistanceSumLimit: jspb.Message.getFieldWithDefault(msg, 28, 0),
    blockchainHeadersCount: jspb.Message.getFieldWithDefault(msg, 29, 0),
    blockchainHeaders: (f = msg.getBlockchainHeaders()) && proto.bc.BlockchainHeaders.toObject(includeInstance, f),
    blockchainFingerprintsRoot: jspb.Message.getFieldWithDefault(msg, 31, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.BcBlock}
 */
proto.bc.BcBlock.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.BcBlock;
  return proto.bc.BcBlock.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.BcBlock} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.BcBlock}
 */
proto.bc.BcBlock.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousHash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSchemaVersion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHeight(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMiner(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDifficulty(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setMerkleRoot(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setChainRoot(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDistance(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTotalDistance(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonce(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNrgGrant(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetHash(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTargetHeight(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetMiner(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetSignature(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTwn(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.addTws(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEmblemWeight(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmblemChainBlockHash(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmblemChainFingerprintRoot(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmblemChainAddress(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTxCount(value);
      break;
    case 26:
      var value = new proto.bc.BcTransaction;
      reader.readMessage(value,proto.bc.BcTransaction.deserializeBinaryFromReader);
      msg.addTxs(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTxFeeBase(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTxDistanceSumLimit(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockchainHeadersCount(value);
      break;
    case 30:
      var value = new proto.bc.BlockchainHeaders;
      reader.readMessage(value,proto.bc.BlockchainHeaders.deserializeBinaryFromReader);
      msg.setBlockchainHeaders(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockchainFingerprintsRoot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.BcBlock.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.BcBlock.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.BcBlock} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BcBlock.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPreviousHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getSchemaVersion();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getMiner();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDifficulty();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getMerkleRoot();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getChainRoot();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getDistance();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
  f = message.getTotalDistance();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getNonce();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getNrgGrant();
  if (f !== 0) {
    writer.writeUint64(
      14,
      f
    );
  }
  f = message.getTargetHash();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getTargetHeight();
  if (f !== 0) {
    writer.writeUint64(
      16,
      f
    );
  }
  f = message.getTargetMiner();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getTargetSignature();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getTwn();
  if (f !== 0) {
    writer.writeUint64(
      19,
      f
    );
  }
  f = message.getTwsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      20,
      f
    );
  }
  f = message.getEmblemWeight();
  if (f !== 0) {
    writer.writeUint64(
      21,
      f
    );
  }
  f = message.getEmblemChainBlockHash();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getEmblemChainFingerprintRoot();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getEmblemChainAddress();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getTxCount();
  if (f !== 0) {
    writer.writeUint64(
      25,
      f
    );
  }
  f = message.getTxsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      26,
      f,
      proto.bc.BcTransaction.serializeBinaryToWriter
    );
  }
  f = message.getTxFeeBase();
  if (f !== 0) {
    writer.writeUint64(
      27,
      f
    );
  }
  f = message.getTxDistanceSumLimit();
  if (f !== 0) {
    writer.writeUint64(
      28,
      f
    );
  }
  f = message.getBlockchainHeadersCount();
  if (f !== 0) {
    writer.writeUint64(
      29,
      f
    );
  }
  f = message.getBlockchainHeaders();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      proto.bc.BlockchainHeaders.serializeBinaryToWriter
    );
  }
  f = message.getBlockchainFingerprintsRoot();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
};


/**
 * optional string hash = 1;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setHash = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string previous_hash = 2;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getPreviousHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setPreviousHash = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint64 version = 3;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setVersion = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint64 schema_version = 4;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getSchemaVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setSchemaVersion = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint64 height = 5;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setHeight = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string miner = 6;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getMiner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setMiner = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional float difficulty = 7;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getDifficulty = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setDifficulty = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional uint64 timestamp = 8;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional string merkle_root = 9;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getMerkleRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setMerkleRoot = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string chain_root = 10;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getChainRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setChainRoot = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional uint64 distance = 11;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getDistance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setDistance = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional uint64 total_distance = 12;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTotalDistance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTotalDistance = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional string nonce = 13;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getNonce = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setNonce = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional uint64 nrg_grant = 14;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getNrgGrant = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setNrgGrant = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional string target_hash = 15;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getTargetHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setTargetHash = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional uint64 target_height = 16;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTargetHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTargetHeight = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional string target_miner = 17;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getTargetMiner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setTargetMiner = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * optional string target_signature = 18;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getTargetSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setTargetSignature = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * optional uint64 twn = 19;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTwn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTwn = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * repeated string tws = 20;
 * @return {!Array.<string>}
 */
proto.bc.BcBlock.prototype.getTwsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 20));
};


/** @param {!Array.<string>} value */
proto.bc.BcBlock.prototype.setTwsList = function(value) {
  jspb.Message.setField(this, 20, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.bc.BcBlock.prototype.addTws = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 20, value, opt_index);
};


proto.bc.BcBlock.prototype.clearTwsList = function() {
  this.setTwsList([]);
};


/**
 * optional uint64 emblem_weight = 21;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getEmblemWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setEmblemWeight = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * optional string emblem_chain_block_hash = 22;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getEmblemChainBlockHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setEmblemChainBlockHash = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * optional string emblem_chain_fingerprint_root = 23;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getEmblemChainFingerprintRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setEmblemChainFingerprintRoot = function(value) {
  jspb.Message.setField(this, 23, value);
};


/**
 * optional string emblem_chain_address = 24;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getEmblemChainAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setEmblemChainAddress = function(value) {
  jspb.Message.setField(this, 24, value);
};


/**
 * optional uint64 tx_count = 25;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTxCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTxCount = function(value) {
  jspb.Message.setField(this, 25, value);
};


/**
 * repeated BcTransaction txs = 26;
 * @return {!Array.<!proto.bc.BcTransaction>}
 */
proto.bc.BcBlock.prototype.getTxsList = function() {
  return /** @type{!Array.<!proto.bc.BcTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bc.BcTransaction, 26));
};


/** @param {!Array.<!proto.bc.BcTransaction>} value */
proto.bc.BcBlock.prototype.setTxsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 26, value);
};


/**
 * @param {!proto.bc.BcTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bc.BcTransaction}
 */
proto.bc.BcBlock.prototype.addTxs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 26, opt_value, proto.bc.BcTransaction, opt_index);
};


proto.bc.BcBlock.prototype.clearTxsList = function() {
  this.setTxsList([]);
};


/**
 * optional uint64 tx_fee_base = 27;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTxFeeBase = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTxFeeBase = function(value) {
  jspb.Message.setField(this, 27, value);
};


/**
 * optional uint64 tx_distance_sum_limit = 28;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getTxDistanceSumLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setTxDistanceSumLimit = function(value) {
  jspb.Message.setField(this, 28, value);
};


/**
 * optional uint64 blockchain_headers_count = 29;
 * @return {number}
 */
proto.bc.BcBlock.prototype.getBlockchainHeadersCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 29, 0));
};


/** @param {number} value */
proto.bc.BcBlock.prototype.setBlockchainHeadersCount = function(value) {
  jspb.Message.setField(this, 29, value);
};


/**
 * optional BlockchainHeaders blockchain_headers = 30;
 * @return {?proto.bc.BlockchainHeaders}
 */
proto.bc.BcBlock.prototype.getBlockchainHeaders = function() {
  return /** @type{?proto.bc.BlockchainHeaders} */ (
    jspb.Message.getWrapperField(this, proto.bc.BlockchainHeaders, 30));
};


/** @param {?proto.bc.BlockchainHeaders|undefined} value */
proto.bc.BcBlock.prototype.setBlockchainHeaders = function(value) {
  jspb.Message.setWrapperField(this, 30, value);
};


proto.bc.BcBlock.prototype.clearBlockchainHeaders = function() {
  this.setBlockchainHeaders(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.bc.BcBlock.prototype.hasBlockchainHeaders = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional string blockchain_fingerprints_root = 31;
 * @return {string}
 */
proto.bc.BcBlock.prototype.getBlockchainFingerprintsRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/** @param {string} value */
proto.bc.BcBlock.prototype.setBlockchainFingerprintsRoot = function(value) {
  jspb.Message.setField(this, 31, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.BcTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.BcTransaction, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.BcTransaction.displayName = 'proto.bc.BcTransaction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.BcTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.BcTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.BcTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BcTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    hash: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.BcTransaction}
 */
proto.bc.BcTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.BcTransaction;
  return proto.bc.BcTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.BcTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.BcTransaction}
 */
proto.bc.BcTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.BcTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.BcTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.BcTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BcTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string hash = 1;
 * @return {string}
 */
proto.bc.BcTransaction.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.BcTransaction.prototype.setHash = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bc.BlockchainHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bc.BlockchainHeader, jspb.Message);
if (true || goog.DEBUG && !COMPILED) {
  proto.bc.BlockchainHeader.displayName = 'proto.bc.BlockchainHeader';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bc.BlockchainHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.bc.BlockchainHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bc.BlockchainHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BlockchainHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockchain: jspb.Message.getFieldWithDefault(msg, 1, ""),
    hash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    previousHash: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    height: jspb.Message.getFieldWithDefault(msg, 5, 0),
    merkleRoot: jspb.Message.getFieldWithDefault(msg, 6, ""),
    blockchainConfirmationsInParentCount: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bc.BlockchainHeader;
  return proto.bc.BlockchainHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bc.BlockchainHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bc.BlockchainHeader}
 */
proto.bc.BlockchainHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBlockchain(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreviousHash(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setHeight(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMerkleRoot(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlockchainConfirmationsInParentCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bc.BlockchainHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bc.BlockchainHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bc.BlockchainHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bc.BlockchainHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlockchain();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPreviousHash();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getMerkleRoot();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBlockchainConfirmationsInParentCount();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
};


/**
 * optional string blockchain = 1;
 * @return {string}
 */
proto.bc.BlockchainHeader.prototype.getBlockchain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.bc.BlockchainHeader.prototype.setBlockchain = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string hash = 2;
 * @return {string}
 */
proto.bc.BlockchainHeader.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.bc.BlockchainHeader.prototype.setHash = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string previous_hash = 3;
 * @return {string}
 */
proto.bc.BlockchainHeader.prototype.getPreviousHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.bc.BlockchainHeader.prototype.setPreviousHash = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional uint64 timestamp = 4;
 * @return {number}
 */
proto.bc.BlockchainHeader.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.bc.BlockchainHeader.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional uint64 height = 5;
 * @return {number}
 */
proto.bc.BlockchainHeader.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.bc.BlockchainHeader.prototype.setHeight = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string merkle_root = 6;
 * @return {string}
 */
proto.bc.BlockchainHeader.prototype.getMerkleRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.bc.BlockchainHeader.prototype.setMerkleRoot = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint64 blockchain_confirmations_in_parent_count = 7;
 * @return {number}
 */
proto.bc.BlockchainHeader.prototype.getBlockchainConfirmationsInParentCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.bc.BlockchainHeader.prototype.setBlockchainConfirmationsInParentCount = function(value) {
  jspb.Message.setField(this, 7, value);
};


goog.object.extend(exports, proto.bc);
